require "entities/statistic"
require "entities/player"
require "entities/player_slugging_percentage"
require "repositories/statistic_repository"
require "repositories/player_repository"
require "queries/get_player_with_most_improved_batting_average"
require "queries/get_player_slugging_percentages"
